export const data = [
  {
    ID: 1,
    "Ad Soyad": "Will Smith",
    Capacity: " No Way",
    Value: 8,
    "Final Status": "Cavab gözləyirik",
    "Contact Number": "+994 512436745",
    "Training Name": "React Basics",
    "Last Contact Date": "2024-01-15",
    "When Call Again": "2024-01-22",
  },
  {
    ID: 2,
    "Ad Soyad": "Ali Mahniu",
    Capacity: " High",
    Value: 6,
    "Final Status": "Maraqlanır",
    "Contact Number": "+994 512436745",
    "Training Name": "Advanced JavaScript",
    "Last Contact Date": "2024-01-10",
    "When Call Again": "2024-01-20",
  },
  {
    ID: 3,
    "Ad Soyad": "Mehemmed Mehemmedova",
    Capacity: " Outstanding",
    Value: 2.5,
    "Final Status": "Almağı düşünür",
    "Contact Number": "+994 512436745",
    "Training Name": "Advanced JavaScript",
    "Last Contact Date": "2024-01-10",
    "When Call Again": "2024-01-20",
  },
  {
    ID: 4,
    "Ad Soyad": "Fidan Mehemmedova",
    Capacity: " Minimum Acceptable",
    Value: 60,
    "Final Status": "Görüş istəyir",
    "Contact Number": "+994 512436745",
    "Training Name": "Advanced JavaScript",
    "Last Contact Date": "2024-01-10",
    "When Call Again": "2024-01-20",
  },
  {
    ID: 5,
    "Ad Soyad": "Claes Helou",
    Capacity: " No Way",
    Value: 60,
    "Final Status": "Alıb",
    "Contact Number": "+994 512436745",
    "Training Name": "Advanced JavaScript",
    "Last Contact Date": "2024-01-10",
    "When Call Again": "2024-01-20",
  },
  {
    ID: 5,
    "Ad Soyad": "Claes Helou",
    Capacity: " No Way",
    Value: 60,
    "Final Status": "Alıb",
    "Contact Number": "+994 512436745",
    "Training Name": "Advanced JavaScript",
    "Last Contact Date": "2024-01-10",
    "When Call Again": "2024-01-20",
  },
  {
    ID: 5,
    "Ad Soyad": "Claes Helou",
    Capacity: " No Way",
    Value: 60,
    "Final Status": "Alıb",
    "Contact Number": "+994 512436745",
    "Training Name": "Advanced JavaScript",
    "Last Contact Date": "2024-01-10",
    "When Call Again": "2024-01-20",
  },
  {
    ID: 5,
    "Ad Soyad": "Claes Helou",
    Capacity: " No Way",
    Value: 60,
    "Final Status": "Alıb",
    "Contact Number": "+994 512436745",
    "Training Name": "Advanced JavaScript",
    "Last Contact Date": "2024-01-10",
    "When Call Again": "2024-01-20",
  },
  {
    ID: 5,
    "Ad Soyad": "Claes Helou",
    Capacity: " No Way",
    Value: 60,
    "Final Status": "Alıb",
    "Contact Number": "+994 512436745",
    "Training Name": "Advanced JavaScript",
    "Last Contact Date": "2024-01-10",
    "When Call Again": "2024-01-20",
  },
  {
    ID: 5,
    "Ad Soyad": "Claes Helou",
    Capacity: " No Way",
    Value: 60,
    "Final Status": "Alıb",
    "Contact Number": "+994 512436745",
    "Training Name": "Advanced JavaScript",
    "Last Contact Date": "2024-01-10",
    "When Call Again": "2024-01-20",
  },
  {
    ID: 1,
    "Ad Soyad": "Will Smith",
    Capacity: " No Way",
    Value: 8,
    "Final Status": "Cavab gözləyirik",
    "Contact Number": "+994 512436745",
    "Training Name": "React Basics",
    "Last Contact Date": "2024-01-15",
    "When Call Again": "2024-01-22",
  },
  {
    ID: 1,
    "Ad Soyad": "Will Smith",
    Capacity: " No Way",
    Value: 8,
    "Final Status": "Cavab gözləyirik",
    "Contact Number": "+994 512436745",
    "Training Name": "React Basics",
    "Last Contact Date": "2024-01-15",
    "When Call Again": "2024-01-22",
  },
  {
    ID: 1,
    "Ad Soyad": "Will Smith",
    Capacity: " No Way",
    Value: 8,
    "Final Status": "Cavab gözləyirik",
    "Contact Number": "+994 512436745",
    "Training Name": "React Basics",
    "Last Contact Date": "2024-01-15",
    "When Call Again": "2024-01-22",
  },
  {
    ID: 1,
    "Ad Soyad": "Will Smith",
    Capacity: " No Way",
    Value: 8,
    "Final Status": "Cavab gözləyirik",
    "Contact Number": "+994 512436745",
    "Training Name": "React Basics",
    "Last Contact Date": "2024-01-15",
    "When Call Again": "2024-01-22",
  },
  {
    ID: 1,
    "Ad Soyad": "Will Smith",
    Capacity: " No Way",
    Value: 8,
    "Final Status": "Cavab gözləyirik",
    "Contact Number": "+994 512436745",
    "Training Name": "React Basics",
    "Last Contact Date": "2024-01-15",
    "When Call Again": "2024-01-22",
  },
  {
    ID: 1,
    "Ad Soyad": "Will Smith",
    Capacity: " No Way",
    Value: 8,
    "Final Status": "Cavab gözləyirik",
    "Contact Number": "+994 512436745",
    "Training Name": "React Basics",
    "Last Contact Date": "2024-01-15",
    "When Call Again": "2024-01-22",
  },
  {
    ID: 1,
    "Ad Soyad": "Will Smith",
    Capacity: " No Way",
    Value: 8,
    "Final Status": "Cavab gözləyirik",
    "Contact Number": "+994 512436745",
    "Training Name": "React Basics",
    "Last Contact Date": "2024-01-15",
    "When Call Again": "2024-01-22",
  },
  {
    ID: 1,
    "Ad Soyad": "Will Smith",
    Capacity: " No Way",
    Value: 8,
    "Final Status": "Cavab gözləyirik",
    "Contact Number": "+994 512436745",
    "Training Name": "React Basics",
    "Last Contact Date": "2024-01-15",
    "When Call Again": "2024-01-22",
  },
  {
    ID: 1,
    "Ad Soyad": "Will Smith",
    Capacity: " No Way",
    Value: 8,
    "Final Status": "Cavab gözləyirik",
    "Contact Number": "+994 512436745",
    "Training Name": "React Basics",
    "Last Contact Date": "2024-01-15",
    "When Call Again": "2024-01-22",
  },
  {
    ID: 2,
    "Ad Soyad": "Ali Mahniu",
    Capacity: " High",
    Value: 6,
    "Final Status": "Maraqlanır",
    "Contact Number": "+994 512436745",
    "Training Name": "Advanced JavaScript",
    "Last Contact Date": "2024-01-10",
    "When Call Again": "2024-01-20",
  },
  {
    ID: 1,
    "Ad Soyad": "Will Smith",
    Capacity: " No Way",
    Value: 8,
    "Final Status": "Cavab gözləyirik",
    "Contact Number": "+994 512436745",
    "Training Name": "React Basics",
    "Last Contact Date": "2024-01-15",
    "When Call Again": "2024-01-22",
  },
  {
    ID: 2,
    "Ad Soyad": "Ali Mahniu",
    Capacity: " High",
    Value: 6,
    "Final Status": "Maraqlanır",
    "Contact Number": "+994 512436745",
    "Training Name": "Advanced JavaScript",
    "Last Contact Date": "2024-01-10",
    "When Call Again": "2024-01-20",
  },
  {
    ID: 1,
    "Ad Soyad": "Will Smith",
    Capacity: " No Way",
    Value: 8,
    "Final Status": "Cavab gözləyirik",
    "Contact Number": "+994 512436745",
    "Training Name": "React Basics",
    "Last Contact Date": "2024-01-15",
    "When Call Again": "2024-01-22",
  },
  {
    ID: 2,
    "Ad Soyad": "Ali Mahniu",
    Capacity: " High",
    Value: 6,
    "Final Status": "Maraqlanır",
    "Contact Number": "+994 512436745",
    "Training Name": "Advanced JavaScript",
    "Last Contact Date": "2024-01-10",
    "When Call Again": "2024-01-20",
  },
];

export const headers = [
  "ID",
  "Ad Soyad",
  "Capacity",
  "Value",
  "Final Status",
  "Contact Number",
  "Training Name",
  "Last Contact Date",
  "When Call Again",
];

export const headersEducation = [
  "ID",
  "Ad Soyad",
  "Background Knowledge",
  "English Level",
  "Sillabusla tanışlıq",
  "University Bachelor",
  "Bachelor Major",
  "Entrance score",
  "Master Degree",
];

export const dataEducation = [
  { 
    ID: 1,
    "Ad Soyad": "Will Smith",
    "Background Knowledge": "Excel",
    "English Level": "B2",
    "Sillabusla tanışlıq": "Məlumatlı",
    "University Bachelor": "ABC University",
    "Bachelor Major": "Computer Science",
    "Entrance score": "503",
    "Master Degree": "Baku Engineering University",
  },
  {
    ID: 2,
    "Ad Soyad": "Ali Mahniu",
    "Background Knowledge": "Excel",
    "English Level": "C1",
    "Sillabusla tanışlıq": "Poor",
    "University Bachelor": "XYZ University",
    "Bachelor Major": "Software Engineering",
    "Entrance score": "670",
    "Master Degree": "Baku Engineering University",
  },
  {
    ID: 3,
    "Ad Soyad": "Sara White",
    "Background Knowledge": "Excel",
    "English Level": "B1",
    "Sillabusla tanışlıq": "Məlumatlı",
    "University Bachelor": "LMN University",
    "Bachelor Major": "Information Systems",
    "Entrance score": "434",
    "Master Degree": "Baku Engineering University",
  },
  {
    ID: 4,
    "Ad Soyad": "James Brown",
    "Background Knowledge": "Excel",
    "English Level": "A2",
    "Sillabusla tanışlıq": "Məlumatsız",
    "University Bachelor": "DEF University",
    "Bachelor Major": "Electrical Engineering",
    "Entrance score": "532",
    "Master Degree": "Baku Engineering University",
  },
  {
    ID: 5,
    "Ad Soyad": "Michael Jordan",
    "Background Knowledge": "Excel",
    "English Level": "C2",
    "Sillabusla tanışlıq": "Məlumatlı",
    "University Bachelor": "GHI University",
    "Bachelor Major": "Mechanical Engineering",
    "Entrance score": "586",
    "Master Degree": "Baku Engineering University",
  },
  {
    ID: 6,
    "Ad Soyad": "Chris Evans",
    "Background Knowledge": "Excel",
    "English Level": "B1",
    "Sillabusla tanışlıq": "Məlumatsız",
    "University Bachelor": "JKL University",
    "Bachelor Major": "Civil Engineering",
    "Entrance score": "427",
    "Master Degree": "Baku Engineering University",
  },
  {
    ID: 7,
    "Ad Soyad": "Emma Stone",
    "Background Knowledge": "Excel",
    "English Level": "B2",
    "Sillabusla tanışlıq": "Poor",
    "University Bachelor": "MNO University",
    "Bachelor Major": "Physics",
    "Entrance score": "612",
    "Master Degree": "Baku Engineering University",
  },
  {
    ID: 8,
    "Ad Soyad": "Ryan Gosling",
    "Background Knowledge": "Excel",
    "English Level": "C1",
    "Sillabusla tanışlıq": "Məlumatlı",
    "University Bachelor": "PQR University",
    "Bachelor Major": "Architecture",
    "Entrance score": "508",
    "Master Degree": "2024-01-15",
  },
  {
    ID: 9,
    "Ad Soyad": "Scarlett Johansson",
    "Background Knowledge": "Excel",
    "English Level": "B2",
    "Sillabusla tanışlıq": "Poor",
    "University Bachelor": "STU University",
    "Bachelor Major": "Biology",
    "Entrance score": "456",
    "Master Degree": "Baku Engineering University",
  },
  {
    ID: 10,
    "Ad Soyad": "Robert Downey Jr.",
    "Background Knowledge": "Excel",
    "English Level": "A1",
    "Sillabusla tanışlıq": "Məlumatlı",
    "University Bachelor": "VWX University",
    "Bachelor Major": "Chemistry",
    "Entrance score": "495",
    "Master Degree": "Baku Engineering University",
  },
];
